### ISSUE TITLE
Failed to execute 'observe' on 'MutationObserver'

### ISSUE THREAD

**Issue by fongandrew** [gadicc/meteor-reactive-window#3] opened 2015-03-06 23:52 UTC
Started seeing their error message in the latest version of Chrome.

```
Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': The value provided is neither an array, nor does it have indexed properties.
```

Triggered by https://github.com/gadicc/meteor-reactive-window/blob/master/reactive-window.js#L100.

**Comment by robmoggach** [comment] 2015-03-16 05:17
Same here:

    Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': The value provided is neither an array, nor does it have indexed properties. reactive-window.js:100
      (anonymous function) jquery.js:3143
      jQuery.Callbacks.firejquery.js:3255
      jQuery.Callbacks.self.fireWithjquery.js:3467
      jQuery.extend.readyjquery.js:3498 completed

**Comment by robmoggach** [comment] 2015-03-16 05:19
I think it's a load order issue - resolved by wrapping in `Meteor.startup  ->` call

**Comment by robmoggach** [comment] 2015-03-16 23:51
my current workaround is here... probably not performant...

    Meteor.startup  ->
      $(window).resize (evt) ->
        Session.set 'touch', new Date
        return
      return

and helper for my 'layout' template...

    Template.layout.helpers
      'touch': ->
        Session.get "touch"

**Comment by zda** [comment] 2015-04-06 10:41
Same issue here. @robmoggach, I couldn't get your workaround to work.

**Comment by productiveme** [comment] 2015-04-09 03:06
+1

**Comment by gadicc** [comment] 2015-04-10 19:49
Hey, I've been unable to reproduce this so it's quite hard to debug but I did make a few changes and maybe it will just work :>  Can someone try 1.0.2 and see if it works any better?

**Comment by productiveme** [comment] 2015-04-11 06:58
Hi Gadi

I did a 

meteor create test
cd test
meteor add gadicohen:reactive-window
meteor

on Mac OSX, browsing to http://locahost:3000 with Google Chrome and opening Dev Tools > Console shows the error. 


On 10 April 2015 at 9:49:21 PM, Gadi Cohen (notifications@github.com) wrote:

Hey, I've been unable to reproduce this so it's quite hard to debug but I did make a few changes and maybe it will just work :> Can someone try 1.0.2 and see if it works any better?

**Comment by gadicc** [comment] 2015-04-12 09:33
Thanks, Jaco.  Still not getting any closer to figuring this out, was googling through various versions of the chrome source code and couldn't find this error message.  I made a new release, `gadicohen:reactive-window@1.0.2-debug.1`, with some extra `console.log()`'s which might give me a better idea of what's happening in these cases.  If you could copy and paste the client console output that would be great, thanks for helping with this.

Everyone else, if you could also confirm your OS and chrome version that would be great.

**Comment by productiveme** [comment] 2015-04-12 16:35
I no longer see the error with a clean meteor test project, but in my timesheets app (http://timesheets.productive.me) I still get the following:

reactive-window.js:94 Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': The value provided is neither an array, nor does it have indexed properties.reactive-window.js:94 (anonymous function)jquery.js:3143 jQuery.Callbacks.firejquery.js:3255 jQuery.Callbacks.self.fireWithjquery.js:3467 jQuery.extend.readyjquery.js:3498 completed


On 12 April 2015 at 11:33:08 AM, Gadi Cohen (notifications@github.com) wrote:

Thanks, Jaco. Still not getting any closer to figuring this out, was googling through various versions of the chrome source code and couldn't find this error message. I made a new release, gadicohen:reactive-window@1.0.2-debug.1, with some extra console.log()'s which might give me a better idea of what's happening in these cases. If you could copy and paste the client console output that would be great, thanks for helping with this.

Everyone else, if you could also confirm your OS and chrome version that would be great.

**Comment by productiveme** [comment] 2015-04-12 16:51
I think the problem lies with the attributeFilter (ln 94) in the following code: its set to true and an array is expected.

// Watch for mutation events
	if (typeof MutationObserver === 'function') {
		var observer = new MutationObserver(lazyUpdate);
		observer.observe(win.document.body, {
			childList: true,
			attributes: true,
			characterData: true,
			subtree: true,
			attributeFilter: true
		});
	} else {
		debug.warn('reactive-window: no MutationObserver, won\'t notice scrollbars');
		// uh, TODO, go back to polling every 100ms
	}


attributeFilter
Set to an array of attribute local names (without namespace) if not all attribute mutations need to be observed.

Jaco Swarts

Productive.me
Cape Town South Africa
Mobile: 082 560 9037
Email: Jaco@productive.me
http://za.linkedin.com/in/jacoswarts
Twitter: @productivedotme


Web & Mobile Application Development
 	Want a signature like this?


On 12 April 2015 at 6:35:33 PM, jaco@productive.me (jaco@productive.me) wrote:

I no longer see the error with a clean meteor test project, but in my timesheets app (http://timesheets.productive.me) I still get the following:

reactive-window.js:94 Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': The value provided is neither an array, nor does it have indexed properties.reactive-window.js:94 (anonymous function)jquery.js:3143 jQuery.Callbacks.firejquery.js:3255 jQuery.Callbacks.self.fireWithjquery.js:3467 jQuery.extend.readyjquery.js:3498 completed


On 12 April 2015 at 11:33:08 AM, Gadi Cohen (notifications@github.com) wrote:

Thanks, Jaco. Still not getting any closer to figuring this out, was googling through various versions of the chrome source code and couldn't find this error message. I made a new release, gadicohen:reactive-window@1.0.2-debug.1, with some extra console.log()'s which might give me a better idea of what's happening in these cases. If you could copy and paste the client console output that would be great, thanks for helping with this.

Everyone else, if you could also confirm your OS and chrome version that would be great.

**Comment by gadicc** [comment] 2015-04-12 17:07
Oh, good work!  I've removed that in `gadicohen:reactive-window@1.0.3`, can you confirm if it solves the problem?

**Comment by productiveme** [comment] 2015-04-12 17:13
I still get the same error, seems its not removed in 1.0.3...

	// Watch for mutation events
	if (typeof MutationObserver === 'function') {
		var observer = new MutationObserver(lazyUpdate);
		observer.observe(win.document.body, {
			childList: true,
			attributes: true,
			characterData: true,
			subtree: true,
			attributeFilter: true
		});
	} else {
		debug.warn('reactive-window: no MutationObserver, won\'t notice scrollbars');
		// uh, TODO, go back to polling every 100ms
	}


Jaco Swarts

Productive.me
Cape Town South Africa
Mobile: 082 560 9037
Email: Jaco@productive.me
http://za.linkedin.com/in/jacoswarts
Twitter: @productivedotme


Web & Mobile Application Development
 	Want a signature like this?


On 12 April 2015 at 7:07:26 PM, Gadi Cohen (notifications@github.com) wrote:

Oh, good work! I've removed that in gadicohen:reactive-window@1.0.3, can you confirm if it solves the problem?

**Comment by gadicc** [comment] 2015-04-12 17:17
Weird, you're right.  Try `gadicohen:reactive-window@1.0.4` :)  Thanks for all your time with this!

**Comment by productiveme** [comment] 2015-04-12 17:23
Shot! 1.0.4 fixes the issue for me.

No problem, thanks for all the packages dude!


On 12 April 2015 at 7:17:12 PM, Gadi Cohen (notifications@github.com) wrote:

Weird, you're right. Try gadicohen:reactive-window@1.0.4 :) Thanks for all your time with this!

**Comment by gadicc** [comment] 2015-04-12 17:27
Amazing!  Pleasure, it's a lot easier when the community helps out, so thanks again :>

**Closed by gadicc** 2015-04-12 17:27 UTC
